SRCS_RACCESS__RACCESS_CONTRAFOLD   = ${SRCS0} run_raccess_contrafold.cpp
OBJS_RACCESS__RACCESS_CONTRAFOLD   = ${SRCS_RACCESS__RACCESS_CONTRAFOLD:.cpp=.o}
OBJS_RACCESS__RACCESS_CONTRAFOLD_D = ${SRCS_RACCESS__RACCESS_CONTRAFOLD:.cpp=.o_D}
run_raccess_contrafold: $(OBJS_RACCESS__RACCESS_CONTRAFOLD)
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^ $(LIBS)
run_raccess_contrafold_D: $(OBJS_RACCESS__RACCESS_CONTRAFOLD_D)
	$(CC) $(CFLAGS_D) $(INCLUDES) -o $@ $^ $(LIBS_D)
EXES_ALL += run_raccess_contrafold
SRCS_ALL += $(SRCS_RACCESS__RACCESS_CONTRAFOLD)
